# In the following buildspec we run the sam commands to build
# package and deploy the lambdas.
# The build is use to build a serverless application and prepares it for 
# subsequent steps in your workflow, like locally 
# testing the application or deploying it to the AWS Cloud.
# Deploy provisions the lambdas on AWS
version: 0.2
phases:
  build:
    commands:
      # Lambdas
      - sam build
      - sam deploy --stack-name vehicle-demo-lambda-stack --s3-bucket $ArtifactsBucketName --capabilities CAPABILITY_NAMED_IAM
  post_build:
    commands:
      # AppSync sam build commands
      - sam package --template-file aws_scripts/appsync_stack.yml --s3-bucket $ArtifactsBucketName --output-template-file packaged.yaml
      - sam deploy --template-file packaged.yaml --stack-name vehicle-demo-appsync-stack --capabilities CAPABILITY_NAMED_IAM