AWSTemplateFormatVersion: 2010-09-09
Description: Template creates roles for Codebuild SAM application
# TODO: Ensure all permissions specify exact resources

Resources:
  CodeBuildIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "codebuild-sam-full-access-${AWS::Region}"
      Description: Provides Codebuild permission to access API GW, Lambda and Cloudformation
      #Provide Codebuild permission to assume this role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Path: "/service-role/"
      Policies:
        - PolicyName: !Sub "codebuild-access-logs-${AWS::Region}"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:logs:eu-west-1:"
                      - !Ref "AWS::AccountId"
                      - ":log-group:/aws/codebuild/"
                      - !ImportValue ProjectName
                  - !Join
                    - ""
                    - - "arn:aws:logs:eu-west-1:"
                      - !Ref "AWS::AccountId"
                      - ":log-group:/aws/codebuild/"
                      - !ImportValue ProjectName
                      - ":*"
                  # - !Sub "arn:aws:logs:eu-west-1:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}"
                  # - !Sub "arn:aws:logs:eu-west-1:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: !Sub "codebuild-access-s3-${AWS::Region}"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - arn:aws:s3:::codepipeline-eu-west-1-*
                  - !Join 
                    - "" 
                    - - "arn:aws:s3:::"
                      - !ImportValue ArtifactBucketName
                  - !Join 
                    - ""
                    - - "arn:aws:s3:::"
                      - !ImportValue ArtifactBucketName
                      - "/*"
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
        - PolicyName: !Sub codebuild-access-reports-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:codebuild:"
                      - !Ref "AWS::Region"
                      - ":"
                      - !Ref "AWS::AccountId"
                      - ":report-group/"
                      - !ImportValue ProjectName
                      - "-*"
                  # - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${ProjectName}-*"
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
        - PolicyName: !Sub codebuild-access-iam-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - '*'
                Action:
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:PassRole
        - PolicyName: !Sub codebuild-ssm-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - '*'
                Action:
                  - ssm:PutParameter
                  - ssm:GetParameters
                  - ssm:DeleteParameters
        - PolicyName: !Sub codebuild-appsync-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - '*'
                Action:
                  - appsync:CreateGraphqlApi
                  - appsync:DeleteGraphqlApi
                  - appsync:UpdateGraphqlApi
                  - appsync:GetGraphqlApi
                  - appsync:StartSchemaCreation
                  - appsync:GetSchemaCreationStatus
                  - appsync:ListTagsForResource
                  - appsync:CreateDataSource
                  - appsync:DeleteDataSource
                  - appsync:GetDataSource
                  - appsync:ListDataSources
                  - appsync:UpdateDataSource
                  - appsync:CreateResolver
                  - appsync:DeleteResolver
                  - appsync:GetResolver
                  - appsync:ListResolvers
                  - appsync:UpdateResolver

Outputs:
  CodeBuildIAMRoleARN:
    Value: !GetAtt CodeBuildIAMRole.Arn
    Export:
      Name: CodeBuildIAMRoleARNs