AWSTemplateFormatVersion: 2010-09-09
Description: Template creates dynamodb table

Parameters:
  TableName:
    Type: String
    Default: "<value>"
    Description: 'table name'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
    # A list of attributes that describe the key schema for the table and indexes.
    # This property is required to create a DynamoDB table.
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        # - AttributeName: sk
        #   AttributeType: S
    # Specifies the attributes that make up the primary key for the table. 
    # The attributes in the KeySchema property must also be defined in the AttributeDefinitions property.
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
        # - AttributeName: sk
        #   KeyType: RANGE
    # Throughput for the specified table, which consists of values for ReadCapacityUnits and WriteCapacityUnits
    # If you set BillingMode as PROVISIONED, you must specify this property. 
    # If you set BillingMode as PAY_PER_REQUEST, you cannot specify this property.
    # If If you set BillingMode is not in the script, you must specify this property
      ProvisionedThroughput: 
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
    # A name for the table. If you don't specify a name, AWS CloudFormation generates 
    # a unique physical ID and uses that ID for the table name.
      TableName: !Ref TableName

# Exports
Outputs:
  DynamoTableArn:
    Value: !GetAtt  UserDynamoDBTable.Arn
    Export:
      Name: DynamoTableArn
  DynamoTableName:
    Value: !Ref TableName
    Export:
      Name: DynamoTableName
