AWSTemplateFormatVersion: 2010-09-09
Description: Template creates artifacts bucket
#comment
######################Parameters#########################
# Parameters are used to receive input from the user for 
# various dynamic attributes in the script. For example
# in this script the user is able to specify the name for
# the artifacts bucket, which will house all the lambdas
Parameters:
  ArtifactsBucketName:
    Type: String
    Default: 'vehicle-demo-vehicle-image-bucket'
    Description: 'Name of s3 bucket'

#######################Resource##########################
# The following section is used to create an aws resource as
# seen with the resource tag. The tag following this called 
# "ArtifactsBucket" specifies a cloudformation logical id for the 
# resource. The type tag specifies the type of resource being 
# created in this case an s3 bucket. The tag "!Ref" is used
# to obtain the name specified in the Parameters section.
Resources:
  VehicleImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactsBucketName
      AccessControl: Private
